import React from 'react'

const Home = () => {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, soluta reiciendis quas odio magni nesciunt, dicta libero corporis aspernatur error molestias, deleniti veritaQuos, iure fugiat! Tenetur doloribus debitis iste aliquid rem ab, voluptates perspiciatis eius cumque consequatur, necessitatibus quaerat omnis sunt voluptatem animi! Ipsam excepturi, consectetur molestiae reprehenderit laboriosam cupiditate incidunt vero delectus eos quidem nemo tenetur veritatis, adipisci a enim soluta, eligendi perferendis omnis labore? Unde, voluptatibus deleniti? Fugit aliquid in eum voluptas, non sapiente aspernatur recusandae necessitatibus dolorum tempore dignissimos velit eos placeat cum doloremque nam voluptatibus sed, perspiciatis possimus vel sequi molestiae enim! Laborum, dolore.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, soluta reiciendis quas odio magni nesciunt, dicta libero corporis aspernatur error molestias, deleniti veritaQuos, iure fugiat! Tenetur doloribus debitis iste aliquid rem ab, voluptates perspiciatis eius cumque consequatur, necessitatibus quaerat omnis sunt voluptatem animi! Ipsam excepturi, consectetur molestiae reprehenderit laboriosam cupiditate incidunt vero delectus eos quidem nemo tenetur veritatis, adipisci a enim soluta, eligendi perferendis omnis labore? Unde, voluptatibus deleniti? Fugit aliquid in eum voluptas, non sapiente aspernatur recusandae necessitatibus dolorum tempore dignissimos velit eos placeat cum doloremque nam voluptatibus sed, perspiciatis possimus vel sequi molestiae enim! Laborum, dolore.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, soluta reiciendis quas odio magni nesciunt, dicta libero corporis aspernatur error molestias, deleniti veritaQuos, iure fugiat! Tenetur doloribus debitis iste aliquid rem ab, voluptates perspiciatis eius cumque consequatur, necessitatibus quaerat omnis sunt voluptatem animi! Ipsam excepturi, consectetur molestiae reprehenderit laboriosam cupiditate incidunt vero delectus eos quidem nemo tenetur veritatis, adipisci a enim soluta, eligendi perferendis omnis labore? Unde, voluptatibus deleniti? Fugit aliquid in eum voluptas, non sapiente aspernatur recusandae necessitatibus dolorum tempore dignissimos velit eos placeat cum doloremque nam voluptatibus sed, perspiciatis possimus vel sequi molestiae enim! Laborum, dolore.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, soluta reiciendis quas odio magni nesciunt, dicta libero corporis aspernatur error molestias, deleniti veritaQuos, iure fugiat! Tenetur doloribus debitis iste aliquid rem ab, voluptates perspiciatis eius cumque consequatur, necessitatibus quaerat omnis sunt voluptatem animi! Ipsam excepturi, consectetur molestiae reprehenderit laboriosam cupiditate incidunt vero delectus eos quidem nemo tenetur veritatis, adipisci a enim soluta, eligendi perferendis omnis labore? Unde, voluptatibus deleniti? Fugit aliquid in eum voluptas, non sapiente aspernatur recusandae necessitatibus dolorum tempore dignissimos velit eos placeat cum doloremque nam voluptatibus sed, perspiciatis possimus vel sequi molestiae enim! Laborum, dolore.</p>
    </div>
  )
}

export default Home